
public class EvenFibonacciNumbers {
	/**
	 * Each new term in the Fibonacci Sequence is generated by adding previous terms. By starting w/ 1 and 2, first 10 terms will be:
	 * 1,2,3,5,8,13,21,34,55,89,..
	 * Fib. seq <= 4million... find sum of even valued terms
	 */
	public static void main(String[] args) {
		int num1 = 0;
		int num2 = 1;
		int temp = 0;
		int sum = 0;
		
		do {
			if(num2% 2 == 0) {
				sum = sum + num2;
			}
			temp = num1 + num2;
			num1 = num2;
			num2 = temp;}
		while(num2<4000000);
		System.out.println(sum);
			}
		
	}


